server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
    sentinel:
      datasource:
        ds1.nacos:
          server-addr: nacos-server:8848
          dataId: gw-flow
          ruleType: gw_flow
        ds2.nacos:
          server-addr: nacos-server:8848
          dataId: api-group
          ruleType: gw_api_group
#      transport:
#        dashboard: sentinel-dashboard:8858
#        port: 8179
#        clientIp: 192.168.137.1

  redis:
    host: redis-server
    port: 6379

