spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-server
      source: createOrder,sendCoinTransferRequest
      bindings:
        createOrder-out-0:
          destination: submittedOrder
          content-type: application/json
        sendCoinTransferRequest-out-0:
          destination: coinTransferRequest
          content-type: application/json
        receiveTradeRecords-in-0:
          destination: tradeRecords
          content-type: application/json
      function:
        definition: receiveTradeRecords
  kafka:
    consumer:
      auto-offset-reset: latest